version: 2.1

commands:
  prebuild:
    steps:
      - run:
          name: Setup executor
          command: |
            apt-get -qq update
            apt-get -q install -y git openssh-client curl ca-certificates make tar gzip
            bash <(curl -fsSL https://get.docker.com)
      - checkout
      - setup_remote_docker:
          version: 20.10.2
      - run:
          name: Setup
          command: |
            git submodule update --init --recursive
            ./deps/readies/bin/getpy3
            docker login --username redisfab --password "$DOCKER_REDISFAB_PWD"

jobs:
  build:
    parameters:
      platform:
        type: string
    docker:
      - image: 'debian:buster'
    steps:
      - prebuild
      - run:
          name: Build
          command: |
            make build publish OSNICK=<<parameters.platform>> X64=1 STD_VERSIONS=1
            # make build publish CROSS=1 OSNICK=<<parameters.platform>> STD_VERSIONS=1
          no_output_timeout: 30m


on-any-branch: &on-any-branch
  filters:
    branches:
      only: /.*/
    tags:
      only: /.*/

never: &never
  filters:
    branches:
      ignore: /.*/
    tags:
      ignore: /.*/


workflows:
  version: 2
  general:
    jobs:
      - build:
          <<: *on-any-branch
          matrix:
            parameters:
              # platform: [centos7, centos8, hirsute, focal, bionic, xenial, trusty, bullseye, buster, fedora33, fedora34, fedora35, alpine3, alpineedge]
              platform: [fedora34, fedora35, alpine3, alpineedge]

  weekly:
    triggers:
      - schedule:
          # Run on Sundat 21:17 [M H DoM M DoW]
          cron: "21 17 * * 0"
          filters:
             branches:
               only:
                 - master
    jobs:
      - build:
          matrix:
            parameters:
              # platform: [centos7, centos8, hirsute, focal, bionic, xenial, trusty, bullseye, buster, fedora33, fedora34, fedora35, alpine3, alpineedge]
              platform: [fedora34, fedora35, alpine3, alpineedge]
